name = "era-dev"
compatibility_date = "2022-06-10"
main = "src/index.js"

kv_namespaces = [
  { binding = "GAME_INFO_DB", id = "00000000000000000000000000000000" }
]

[env.production]
name = "era"
kv_namespaces = [
  { binding = "GAME_INFO_DB", id = "4ed55184883b4e8fb4bd9cb07634ee2e" }
]

[env.production.vars]
ENVIRONMENT = "production"
GITHUB_REPO_URL = "https://github.com/1ackbfun/era-info-api"
